/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodstem.frame;

import foodstem.service.InventoryService;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andrei
 */
public class Inventory extends javax.swing.JFrame {

        
    private final InventoryService inventoryService = new InventoryService();
    
    
    
public Inventory() {
    
    initComponents();          

    // NU mai punem setSize aici
    setLocationRelativeTo(null);  
    setResizable(false);          
    
    
    jComboBox1.removeAllItems();
    jComboBox1.addItem("Burger");
    jComboBox1.addItem("Wrap");
    jComboBox1.addItem("Fries");
    jComboBox1.addItem("Soda");
    jComboBox1.addItem("Dessert");
    jComboBox1.addItem("Sandwich");

    jTable_1.setDefaultEditor(Object.class, null);

    jTable_1.getSelectionModel().addListSelectionListener(e -> {
        int row = jTable_1.getSelectedRow();
        if (row >= 0) {
            
            jtxtName.setText(jTable_1.getValueAt(row, 1).toString());
            jComboBox1.setSelectedItem(jTable_1.getValueAt(row, 2).toString());
            jtxtQuantity.setText(jTable_1.getValueAt(row, 3).toString());
            jtxtPricepu.setText(jTable_1.getValueAt(row, 4).toString());
            jtxtTotalprice.setText(jTable_1.getValueAt(row, 5).toString());
        }
    });

    loadTableData();
}
    
    
    
    
        
        // Metod that load everyting from database
private void loadTableData() {
    // 1. Take product
    java.util.List<Object[]> items = inventoryService.findAllItems();

    // 2. Take table model
    DefaultTableModel model = (DefaultTableModel) jTable_1.getModel();

    // 3. Delete
    model.setRowCount(0);

    
    int rowNumber = 1;
    for (Object[] row : items) {
        // row contain: { Item_ID, Item_Name, Category, Quantity, Price_Per_Unit, Total_Price }
        // Show in order
        model.addRow(new Object[]{
            rowNumber++,                    // Number order (1, 2, 3...)
            row[1],                         // Item_Name
            row[2],                         // Category
            row[3],                         // Quantity
            row[4],                         // Price_Per_Unit
            row[5]                          // Total_Price
        });
    }
}
    
    

// method that calculate Total Price
private void updateTotalPrice() {
    try {
        String qtyText = jtxtQuantity.getText().trim();
        String priceText = jtxtPricepu.getText().trim();

        if (qtyText.isEmpty() || priceText.isEmpty()) {
            jtxtTotalprice.setText("");
            return;
        }

        int qty = Integer.parseInt(qtyText);
        float price = Float.parseFloat(priceText);
        float total = qty * price;

        jtxtTotalprice.setText(String.format("%.2f", total));
    } catch (NumberFormatException e) {
        
        jtxtTotalprice.setText("");
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_1 = new javax.swing.JTable();
        jlabelSearch = new javax.swing.JLabel();
        jTextField_search = new javax.swing.JTextField();
        jbuttonSearch = new javax.swing.JButton();
        jlabelItemname = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jlabelQuantity = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jlabelPpunit = new javax.swing.JLabel();
        jtxtPricepu = new javax.swing.JTextField();
        jlabelTotalprice = new javax.swing.JLabel();
        jtxtTotalprice = new javax.swing.JTextField();
        jbuttonEnter = new javax.swing.JButton();
        jbuttonClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        javax.swing.JButton jbuttonHome = new javax.swing.JButton();
        javax.swing.JButton jbuttonInventory = new javax.swing.JButton();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JButton jbuttonExit = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jbuttonDelete = new javax.swing.JButton();
        jbuttonModify = new javax.swing.JButton();
        jlabelItemid1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item Name", "Category", "Quantity", "Total Price"
            }
        ));
        jTable_1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable_1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable_1);

        jlabelSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 11)); // NOI18N
        jlabelSearch.setForeground(new java.awt.Color(102, 102, 102));
        jlabelSearch.setText("Search product");

        jbuttonSearch.setText("Search");
        jbuttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonSearchActionPerformed(evt);
            }
        });

        jlabelItemname.setText("Item Name");

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jlabelQuantity.setText("Quantity");

        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });
        jtxtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtQuantityKeyReleased(evt);
            }
        });

        jlabelPpunit.setText("Price Per Unit");

        jtxtPricepu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPricepuActionPerformed(evt);
            }
        });
        jtxtPricepu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPricepuKeyReleased(evt);
            }
        });

        jlabelTotalprice.setText("Total Price");

        jtxtTotalprice.setEditable(false);
        jtxtTotalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalpriceActionPerformed(evt);
            }
        });

        jbuttonEnter.setText("Enter");
        jbuttonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonEnterActionPerformed(evt);
            }
        });

        jbuttonClear.setText("Clear");
        jbuttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(82, 109, 130));

        jbuttonHome.setBackground(new java.awt.Color(204, 204, 204));
        jbuttonHome.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbuttonHome.setText("Home");
        jbuttonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonHomeActionPerformed(evt);
            }
        });

        jbuttonInventory.setBackground(new java.awt.Color(204, 204, 204));
        jbuttonInventory.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbuttonInventory.setText("Inventory");
        jbuttonInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonInventoryActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(227, 225, 217));
        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(227, 225, 217));
        jLabel11.setText("Inventory");

        jbuttonExit.setBackground(new java.awt.Color(204, 204, 204));
        jbuttonExit.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jbuttonExit.setText("Exit");
        jbuttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonExitActionPerformed(evt);
            }
        });

        jPanel29.setBackground(new java.awt.Color(241, 240, 232));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jbuttonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(62, 62, 62)
                .addComponent(jbuttonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jbuttonDelete.setText("Delete");
        jbuttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDeleteActionPerformed(evt);
            }
        });

        jbuttonModify.setText("Modify");
        jbuttonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonModifyActionPerformed(evt);
            }
        });

        jlabelItemid1.setText("Category");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlabelPpunit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelItemname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlabelTotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtPricepu, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(jtxtQuantity)
                                    .addComponent(jtxtName)
                                    .addComponent(jtxtTotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbuttonModify, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbuttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbuttonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(61, 61, 61)
                                    .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabelItemid1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbuttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jlabelSearch))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuttonSearch)
                            .addComponent(jTextField_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabelItemid1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabelItemname))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelQuantity)
                                    .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPricepu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlabelPpunit)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabelTotalprice)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtxtTotalprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbuttonClear)
                                            .addComponent(jbuttonEnter))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jbuttonModify)
                                            .addComponent(jbuttonDelete))))))))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonHomeActionPerformed
    this.setVisible(false); 
    ManagmentSystem home = new ManagmentSystem();
    home.setVisible(true);  
    }//GEN-LAST:event_jbuttonHomeActionPerformed

    
    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed

    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed

    }//GEN-LAST:event_jtxtQuantityActionPerformed

    private void jtxtPricepuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPricepuActionPerformed
   
    }//GEN-LAST:event_jtxtPricepuActionPerformed

    private void jtxtTotalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalpriceActionPerformed
       
    }//GEN-LAST:event_jtxtTotalpriceActionPerformed

    private void jbuttonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonEnterActionPerformed
    
    
    
    String itemName = jtxtName.getText().trim();
    String quantityText = jtxtQuantity.getText().trim();
    String pricePerUnitText = jtxtPricepu.getText().trim();
    
    String category = jComboBox1.getSelectedItem().toString();
    

    
    if (itemName.isEmpty() ||
        quantityText.isEmpty() || pricePerUnitText.isEmpty()) {
        
        JOptionPane.showMessageDialog(this,
                "Please fill Item ID, Item Name, Quantity and Price Per Unit.");
        return; }

    try {
        
        int quantity = Integer.parseInt(quantityText);
        float pricePerUnit = Float.parseFloat(pricePerUnitText);

        
        float totalPrice = quantity * pricePerUnit;

        
        jtxtTotalprice.setText(String.valueOf(totalPrice));

        
        boolean ok = inventoryService.addItem(
                itemName,
                category,
                quantity,
                pricePerUnit,
                totalPrice
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Item added successfully!");

            loadTableData();

            // 6. Golim câmpurile
            
            jtxtName.setText("");
            jtxtQuantity.setText("");
            jtxtPricepu.setText("");
            jtxtTotalprice.setText("");

        } else {
            JOptionPane.showMessageDialog(this,
                    "Error adding the item to the database.");
        }

    } catch (NumberFormatException ex) {
        
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Enter valid numbers for Quantity and Price Per Unit.");
    }

    
    }//GEN-LAST:event_jbuttonEnterActionPerformed

    private void jbuttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearActionPerformed
       
       jtxtName.setText("");
       jtxtQuantity.setText("");
       jtxtPricepu.setText("");
       jtxtTotalprice.setText("");
    }//GEN-LAST:event_jbuttonClearActionPerformed
     
    private void jbuttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonSearchActionPerformed

        
        
        String searchText = jTextField_search.getText().trim();

        if (searchText.isEmpty()) {
            loadTableData(); // încarcă tot
            return;
        }

            // call service
            java.util.List<Object[]> results = inventoryService.searchItems(searchText);

            // the jtabel model
            DefaultTableModel model = (DefaultTableModel) jTable_1.getModel();

            // clean old table
            model.setRowCount(0);

            // if nothing is find in db
            if (results.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "No products found for: " + searchText);
                return;
            }

            // add in the table what we find in db
            for (Object[] row : results) {
                model.addRow(row);
            }

    }//GEN-LAST:event_jbuttonSearchActionPerformed

    private void jbuttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDeleteActionPerformed
  

    int selectedRow = jTable_1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the table to delete.");
        return;
    }

    
    Object idObj = jTable_1.getValueAt(selectedRow, 0);
    int itemId;

    try {
        itemId = Integer.parseInt(idObj.toString());
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid ID in table. Make sure column 0 is Item_ID.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete item with ID: " + itemId + "?",
            "Confirm delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    boolean ok = inventoryService.deleteItem(itemId);

    if (ok) {
        ((DefaultTableModel) jTable_1.getModel()).removeRow(selectedRow);

        
        jtxtName.setText("");
        jtxtQuantity.setText("");
        jtxtPricepu.setText("");
        jtxtTotalprice.setText("");

        JOptionPane.showMessageDialog(this, "Product deleted successfully!");
    } else {
        JOptionPane.showMessageDialog(this, "Error deleting the product from database.");
    }
    
    }//GEN-LAST:event_jbuttonDeleteActionPerformed



    private void jbuttonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonModifyActionPerformed

 int selectedRow = jTable_1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product from the table to modify.");
        return;
    }

    int itemId = Integer.parseInt(jTable_1.getValueAt(selectedRow, 0).toString());

    String itemName = jtxtName.getText().trim();
    String quantityText = jtxtQuantity.getText().trim();
    String pricePerUnitText = jtxtPricepu.getText().trim();
    String category = jComboBox1.getSelectedItem().toString();

    if (itemName.isEmpty() || quantityText.isEmpty() || pricePerUnitText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill Item Name, Quantity and Price Per Unit.");
        return;
    }

    try {
        int quantity = Integer.parseInt(quantityText);
        float pricePerUnit = Float.parseFloat(pricePerUnitText);

        float totalPrice = quantity * pricePerUnit;
        jtxtTotalprice.setText(String.format("%.2f", totalPrice));

        boolean ok = inventoryService.updateItem(
                itemId,
                itemName,
                category,
                quantity,
                pricePerUnit,
                totalPrice
        );

        if (ok) {
            JOptionPane.showMessageDialog(this, "Product updated successfully!");

            DefaultTableModel model = (DefaultTableModel) jTable_1.getModel();
            
            model.setValueAt(itemName, selectedRow, 1);
            model.setValueAt(category, selectedRow, 2);
            model.setValueAt(quantity, selectedRow, 3);
            model.setValueAt(pricePerUnit, selectedRow, 4);
            model.setValueAt(totalPrice, selectedRow, 5);

        } else {
            JOptionPane.showMessageDialog(this, "Error updating the product in the database.");
        }

    } catch (NumberFormatException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Enter valid numbers for Quantity and Price Per Unit.");
    }

    }//GEN-LAST:event_jbuttonModifyActionPerformed

    private void jbuttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbuttonExitActionPerformed

    private void jTable_1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable_1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_1AncestorAdded

    private void jtxtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtQuantityKeyReleased
        // TODO add your handling code here:
                
       updateTotalPrice();
        
    }//GEN-LAST:event_jtxtQuantityKeyReleased

    private void jtxtPricepuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPricepuKeyReleased
        // TODO add your handling code here:
            
       updateTotalPrice();
        
    }//GEN-LAST:event_jtxtPricepuKeyReleased

    private void jbuttonInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonInventoryActionPerformed
   
        this.setVisible(false); 
        Inventory inv = new Inventory();
        inv.setVisible(true);           
    }//GEN-LAST:event_jbuttonInventoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_1;
    private javax.swing.JTextField jTextField_search;
    private javax.swing.JButton jbuttonClear;
    private javax.swing.JButton jbuttonDelete;
    private javax.swing.JButton jbuttonEnter;
    private javax.swing.JButton jbuttonModify;
    private javax.swing.JButton jbuttonSearch;
    private javax.swing.JLabel jlabelItemid1;
    private javax.swing.JLabel jlabelItemname;
    private javax.swing.JLabel jlabelPpunit;
    private javax.swing.JLabel jlabelQuantity;
    private javax.swing.JLabel jlabelSearch;
    private javax.swing.JLabel jlabelTotalprice;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPricepu;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextField jtxtTotalprice;
    // End of variables declaration//GEN-END:variables
}
